services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/migration:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend/backend/backend # La carpeta donde está tu Dockerfile
      dockerfile: Dockerfile # Nombre de tu Dockerfile (por defecto Dockerfile)
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MEDIA_UPLOAD_DIR: ${MEDIA_UPLOAD_DIR}
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
